# Site settings
title: Cynthia Martinez
email: cynthia.mtnz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website that will contain my programming projects, electronic projects,
  video projects, and graphic design projects. Blog posts with tutorials and research
  will also be provided.

url: "http://cm00100.github.io" # the base hostname & protocol for your site

github_username:  cm00100



# Build settings
markdown: redcarpet

exclude: ['README.md']

