
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"



title: Cynthia Martinez
subtitle: "Cynthia Martinez - Portfolio"
url: "http://cynthiadev.com"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

email: cynthia.mtnz@gmail.com
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"


